export const priceMetall = [
  {
    id: 1,
    name: "Чёрный лом",
    slug: "чёрный_лом",
    subCategory: [
      {
        id: 1,
        name: "Сталь",
        prices: [
          {
            id: 1,
            name: "Чермет габарит - 3А",
            bank_card_price: "26100 руб",
            from_to_price: "26000 руб",
            to_price: "16500 руб",
          },
          {
            id: 2,
            name: "Чермет негабарит - 5А",
            bank_card_price: "26100 руб",
            from_to_price: "26000 руб",
            to_price: "16500 руб",
          },
          {
            id: 3,
            name: "Жесть/Оцинковка - 12А",
            bank_card_price: "26100 руб",
            from_to_price: "26000 руб",
            to_price: "16500 руб",
          },
          {
            id: 4,
            name: "Лом стали 3АМ",
            bank_card_price: "26200 руб",
            from_to_price: "26000 руб",
            to_price: "16200 руб",
          },
          {
            id: 5,
            name: "Лом стали 3А2",
            bank_card_price: "26200 руб",
            from_to_price: "26000 руб",
            to_price: "16200 руб",
          },
          {
            id: 6,
            name: "Лом стали 5АР",
            bank_card_price: "26200 руб",
            from_to_price: "26000 руб",
            to_price: "16300 руб",
          },
          {
            id: 7,
            name: "Лом стали 5АБ",
            bank_card_price: "26200 руб",
            from_to_price: "26000 руб",
            to_price: "16300 руб",
          },
          {
            id: 8,
            name: "Лом стали 5АМ",
            bank_card_price: "26200 руб",
            from_to_price: "26000 руб",
            to_price: "16200 руб",
          },
        ],
      },
      {
        id: 2,
        name: "Лом чугуна",
        prices: [
          {
            id: 1,
            name: "Чугун габарит - 17А",
            bank_card_price: "26100 руб",
            from_to_price: "26000 руб",
            to_price: "16500 руб",
          },
          {
            id: 2,
            name: "Черный металл",
            bank_card_price: "26100 руб",
            from_to_price: "26000 руб",
            to_price: "16500 руб",
          },
          {
            id: 3,
            name: "Чугун негабарит - 20А",
            bank_card_price: "26100 руб",
            from_to_price: "26000 руб",
            to_price: "16500 руб",
          },
          {
            id: 4,
            name: "Чугунные трубы",
            bank_card_price: "26200 руб",
            from_to_price: "26000 руб",
            to_price: "16200 руб",
          },
          {
            id: 5,
            name: "Чугунные плиты",
            bank_card_price: "26200 руб",
            from_to_price: "26000 руб",
            to_price: "16200 руб",
          },
          {
            id: 6,
            name: "Чугунные радиаторы",
            bank_card_price: "26200 руб",
            from_to_price: "26000 руб",
            to_price: "16300 руб",
          },
          {
            id: 7,
            name: "Чугунные ванны",
            bank_card_price: "26200 руб",
            from_to_price: "26000 руб",
            to_price: "16300 руб",
          },
          {
            id: 8,
            name: "Чугунные люки",
            bank_card_price: "26200 руб",
            from_to_price: "26000 руб",
            to_price: "16200 руб",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Цветной лом",
    slug: "цветной_лом",
    subCategory: [
      {
        id: 1,
        name: "Медь",
        prices: [
          {
            id: 1,
            name: "Медь Блестящая (кабель)",
            bank_card_price: "725 руб",
            from_to_price: "723 руб",
            to_price: "723 руб",
          },
          {
            id: 2,
            name: "Медь Кусковая (кабель от 4 мм)",
            bank_card_price: "725 руб",
            from_to_price: "723 руб",
            to_price: "723 руб",
          },
          {
            id: 3,
            name: "Медь Несортовая (Микс)",
            bank_card_price: "725 руб",
            from_to_price: "723 руб",
            to_price: "723 руб",
          },
          {
            id: 4,
            name: "Блестящая (кабель, жила от 2-4 мм)",
            bank_card_price: "725 руб",
            from_to_price: "723 руб",
            to_price: "723 руб",
          },
          {
            id: 5,
            name: "Блестящая (жила 0,5 -2,0 мм)",
            bank_card_price: "725 руб",
            from_to_price: "723 руб",
            to_price: "723 руб",
          },
          {
            id: 6,
            name: "Микс (несортовой лом)",
            bank_card_price: "725 руб",
            from_to_price: "723 руб",
            to_price: "723 руб",
          },
          {
            id: 7,
            name: "Луженая (Засор 7%)",
            bank_card_price: "725 руб",
            from_to_price: "723 руб",
            to_price: "723 руб",
          },
          {
            id: 8,
            name: "Кабель силовой в изоляции (блест жила от 2-4 мм)",
            bank_card_price: "725 руб",
            from_to_price: "723 руб",
            to_price: "723 руб",
          },
        ],
      },
      {
        id: 2,
        name: "Алюминий",
        prices: [
          {
            id: 1,
            name: "Алюминий Электротехнический",
            bank_card_price: "175 руб",
            from_to_price: "173 руб",
            to_price: "173 руб",
          },
          {
            id: 2,
            name: "Алюминий Пищевой",
            bank_card_price: "175 руб",
            from_to_price: "173 руб",
            to_price: "173 руб",
          },
          {
            id: 3,
            name: "Алюминий Профиль",
            bank_card_price: "175 руб",
            from_to_price: "173 руб",
            to_price: "173 руб",
          },
          {
            id: 4,
            name: "Алюминий Микс",
            bank_card_price: "175 руб",
            from_to_price: "173 руб",
            to_price: "173 руб",
          },
          {
            id: 5,
            name: "Алюминий Картерный",
            bank_card_price: "175 руб",
            from_to_price: "173 руб",
            to_price: "173 руб",
          },
          {
            id: 6,
            name: "Алюминиевая стружка",
            bank_card_price: "175 руб",
            from_to_price: "173 руб",
            to_price: "173 руб",
          },
          {
            id: 7,
            name: "Алюминиевые радиаторы",
            bank_card_price: "175 руб",
            from_to_price: "173 руб",
            to_price: "173 руб",
          },
          {
            id: 8,
            name: "Опалубка АД31",
            bank_card_price: "175 руб",
            from_to_price: "173 руб",
            to_price: "173 руб",
          },
        ],
      },
      {
        id: 2,
        name: "Нержавеющая сталь",
        prices: [
          {
            id: 1,
            name: "Нержавеющая сталь",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 2,
            name: "Нержавейка 10% (габарит)",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 3,
            name: "Лом нержавейки 10% (негабарит)",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 4,
            name: "Нержавейка 8% (габарит)",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 5,
            name: "Лом нержавейки 8% (негабарит)",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 6,
            name: "3Б26 Ni 8%",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 7,
            name: "3Б26 Ni 10%",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 8,
            name: "5Б26 Ni 10%",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
        ],
      },
      {
        id: 3,
        name: "Нержавеющая сталь",
        prices: [
          {
            id: 1,
            name: "Нержавеющая сталь",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 2,
            name: "Нержавейка 10% (габарит)",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 3,
            name: "Лом нержавейки 10% (негабарит)",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 4,
            name: "Нержавейка 8% (габарит)",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 5,
            name: "Лом нержавейки 8% (негабарит)",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 6,
            name: "3Б26 Ni 8%",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 7,
            name: "3Б26 Ni 10%",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 8,
            name: "5Б26 Ni 10%",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
        ],
      },
      {
        id: 4,
        name: "Нержавеющая сталь",
        prices: [
          {
            id: 1,
            name: "Нержавеющая сталь",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 2,
            name: "Нержавейка 10% (габарит)",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 3,
            name: "Лом нержавейки 10% (негабарит)",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 4,
            name: "Нержавейка 8% (габарит)",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 5,
            name: "Лом нержавейки 8% (негабарит)",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 6,
            name: "3Б26 Ni 8%",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 7,
            name: "3Б26 Ni 10%",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 8,
            name: "5Б26 Ni 10%",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
        ],
      },
      {
        id: 5,
        name: "Нержавеющая сталь",
        prices: [
          {
            id: 1,
            name: "Нержавеющая сталь",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 2,
            name: "Нержавейка 10% (габарит)",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 3,
            name: "Лом нержавейки 10% (негабарит)",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 4,
            name: "Нержавейка 8% (габарит)",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 5,
            name: "Лом нержавейки 8% (негабарит)",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 6,
            name: "3Б26 Ni 8%",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 7,
            name: "3Б26 Ni 10%",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
          {
            id: 8,
            name: "5Б26 Ni 10%",
            bank_card_price: "88  руб",
            from_to_price: "86 руб",
            to_price: "86 руб",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Кабель б/у",
    slug: "кабель_б_у",
    subCategory: [
      {
        id: 1,
        name: "Кабель",
        prices: [
          {
            id: 1,
            name: "Медь Кусковая (кабель от 4 мм)",
            bank_card_price: "725 руб",
            from_to_price: "723 руб",
            to_price: "723 руб",
          },
          {
            id: 2,
            name: "Медь Несортовая (Микс)",
            bank_card_price: "725 руб",
            from_to_price: "723 руб",
            to_price: "723 руб",
          },
          {
            id: 3,
            name: "Медный Кабель Силовой",
            bank_card_price: "725 руб",
            from_to_price: "723 руб",
            to_price: "723 руб",
          },
          {
            id: 4,
            name: "Свинец кабельный",
            bank_card_price: "725 руб",
            from_to_price: "723 руб",
            to_price: "723 руб",
          },
          {
            id: 5,
            name: "Алюминиевый Кабель",
            bank_card_price: "725 руб",
            from_to_price: "723 руб",
            to_price: "723 руб",
          },
          {
            id: 6,
            name: "Алюминиевый Кабель",
            bank_card_price: "725 руб",
            from_to_price: "723 руб",
            to_price: "723 руб",
          },
          {
            id: 7,
            name: "Кабель в изоляции",
            bank_card_price: "725 руб",
            from_to_price: "723 руб",
            to_price: "723 руб",
          },
          {
            id: 8,
            name: "Неочищенный кабель",
            bank_card_price: "725 руб",
            from_to_price: "723 руб",
            to_price: "723 руб",
          },
        ],
      },
    ],
  }
];
